#!/bin/bash

# generative model without property prediction
python train_graph_vae.py
# models with property prediction for inverse design
python train_graph_vae.py --use_cached_dataset --properties=homo,lumo,r2
python train_graph_vae.py --use_cached_dataset --properties=homo,lumo,r2 --property_latent_dim=16
# models for single property inverse design
python train_graph_vae.py --use_cached_dataset --properties=homo
python train_graph_vae.py --use_cached_dataset --properties=homo --property_latent_dim=16
python train_graph_vae.py --use_cached_dataset --properties=lumo
python train_graph_vae.py --use_cached_dataset --properties=lumo --property_latent_dim=16
python train_graph_vae.py --use_cached_dataset --properties=r2
python train_graph_vae.py --use_cached_dataset --properties=r2 --property_latent_dim=16