#!/bin/bash
python train_graph_vae.py --properties=lumo --use_cached_dataset --epochs=500 --logdir=graph_vae_lumo
python train_graph_vae.py --properties=lumo --use_cached_dataset --epochs=500 --logdir=graph_vae_lumo --property_latent_dim=16