#!/bin/bash

python train_mixture_model.py --use_cached_dataset --epochs=20 --num_clusters=1
python train_mixture_model.py --use_cached_dataset --epochs=20 --num_clusters=2
python train_mixture_model.py --use_cached_dataset --epochs=20 --num_clusters=4
python train_mixture_model.py --use_cached_dataset --epochs=20 --num_clusters=8
python train_mixture_model.py --use_cached_dataset --epochs=20 --num_clusters=16
python train_mixture_model.py --use_cached_dataset --epochs=20 --num_clusters=32
python train_mixture_model.py --use_cached_dataset --epochs=20 --num_clusters=64
python train_mixture_model.py --use_cached_dataset --epochs=20 --num_clusters=128