#!/bin/bash
python train_graph_vae.py --properties=lumo --use_cached_dataset --epochs=500 --logdir=graph_vae_lumo --latent_dim=128
python train_graph_vae.py --properties=lumo --use_cached_dataset --epochs=500 --logdir=graph_vae_lumo --latent_dim=128 --property_latent_dim=16